name: Build and test project
on: [ push ]
jobs:
  build-and-run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper work1
        run: cd work1 && ./gradlew build
      - name: Run build with Gradle Wrapper work4
        run: cd work4 && ./gradlew build
